insert into produto (cod_produto, nome, valor) values (1, 'Mouse Logitech g403', 209.00);
insert into produto (cod_produto, nome, valor) values (2, 'Mouse Redragon cobra', 114.90);
insert into produto (cod_produto, nome, valor) values (3, 'Mouse Mancer crow', 109.90);
insert into produto (cod_produto, nome, valor) values (4, 'Mouse Razer Deathadder', 125.00);
insert into produto (cod_produto, nome, valor) values (5, 'Mouse Razer Viper mini', 140.00);
insert into produto (cod_produto, nome, valor) values (6, 'Mouse Logitech g502', 298.56);
insert into produto (cod_produto, nome, valor) values (7, 'Mouse Logitech g203', 135.90);
insert into produto (cod_produto, nome, valor) values (8, 'Mouse Redragon Impact', 202.89);
insert into produto (cod_produto, nome, valor) values (9, 'Mouse Redragon Griffin', 109.16);
insert into produto (cod_produto, nome, valor) values (10, 'Mouse HyperX Pulsefire', 149.90);
insert into produto (cod_produto, nome, valor) values (11, 'Mousepad Gamer Havit Médio', 36.90);
insert into produto (cod_produto, nome, valor) values (12, 'Mousepad Gamer HyperX Fury S', 149.90);
insert into produto (cod_produto, nome, valor) values (13, 'Mouse Pad Gamer Force One Skyhawk', 89.90);
insert into produto (cod_produto, nome, valor) values (14, 'Mousepad Gamer Husky Gaming Storm', 45.90);
insert into produto (cod_produto, nome, valor) values (15, 'Mousepad Gamer Redragon Pisces', 29.89);
insert into produto (cod_produto, nome, valor) values (16, 'Mousepad Gamer Redragon Neptune', 164.89);
insert into produto (cod_produto, nome, valor) values (17, 'Mousepad Gamer Redragon Capricorn', 29.89);
insert into produto (cod_produto, nome, valor) values (18, 'Mousepad Zowie GTF-X', 299.90);
insert into produto (cod_produto, nome, valor) values (19, 'Mousepad Gamer Redragon Taurus', 82.50);
insert into produto (cod_produto, nome, valor) values (20, 'Mousepad Gamer Mancer Dark Scroll', 94.90);
insert into produto (cod_produto, nome, valor) values (21, 'Placa de Vídeo Zotac Gaming NVIDIA GeForce RTX 2060', 3399.90);
insert into produto (cod_produto, nome, valor) values (22, 'Placa de Vídeo Zotac NVIDIA GeForce RTX 3060 Ti', 4799.90);
insert into produto (cod_produto, nome, valor) values (23, 'Placa de Vídeo Zotac Gaming NVIDIA Geforce RTX 3050', 2899.90);
insert into produto (cod_produto, nome, valor) values (24, 'Placa de Vídeo Pcyes AMD Radeon RX 550', 1049.90);
insert into produto (cod_produto, nome, valor) values (25, 'Placa de Vídeo Asus NVIDIA GeForce GTX 1650', 1999.90);
insert into produto (cod_produto, nome, valor) values (26, 'Placa de Vídeo Gigabyte NVIDIA GeForce RTX 2060', 3199.90);
insert into produto (cod_produto, nome, valor) values (27, 'Placa de Vídeo Sapphire Pulse RX 6500 XT', 1999.90);
insert into produto (cod_produto, nome, valor) values (28, 'Placa de Vídeo Asus NVIDIA GeForce GTX 1050 Ti', 1899.90);
insert into produto (cod_produto, nome, valor) values (29, 'Placa de Vídeo Asus Dual RX 6600 XT', 3799.90);
insert into produto (cod_produto, nome, valor) values (30, 'Placa de Vídeo Galax NVIDIA GeForce GT 210', 229.90);
insert into produto (cod_produto, nome, valor) values (31, 'Teclado Mecânico Gamer T-Dagger Bora', 159.90);
insert into produto (cod_produto, nome, valor) values (32, 'Teclado Mecânico Gamer Redragon Kumara', 199.90);
insert into produto (cod_produto, nome, valor) values (33, 'Teclado Mecânico Gamer HyperX Alloy Origins Core', 499.90);
insert into produto (cod_produto, nome, valor) values (34, 'Teclado Mecânico Gamer HyperX Alloy Origins', 489.90);
insert into produto (cod_produto, nome, valor) values (35, 'Teclado Mecânico Gamer Husky Gaming Blizzard', 209.90);
insert into produto (cod_produto, nome, valor) values (36, 'Teclado Padrão Maxprint USB Preto', 39.90);
insert into produto (cod_produto, nome, valor) values (37, 'Teclado Multilaser ABNT2', 29.90);
insert into produto (cod_produto, nome, valor) values (38, 'Teclado Multilaser Multimídia USB Preto', 34.90);
insert into produto (cod_produto, nome, valor) values (39, 'Teclado Bright Padrão ABNT2 USB Preto', 34.90);
insert into produto (cod_produto, nome, valor) values (40, 'Teclado sem fio Logitech K270', 149.90);
insert into produto (cod_produto, nome, valor) values (41, 'Gabinete Fortrek ATX, Preto', 349.90);
insert into produto (cod_produto, nome, valor) values (42, 'Gabinete Rise Mode Glass 06', 449.90);
insert into produto (cod_produto, nome, valor) values (43, 'Gabinete NOX MODUS ATX', 349.90);
insert into produto (cod_produto, nome, valor) values (44, 'Gabinete Sharkoon Skiller SGC1 Window - Black', 449.90);
insert into produto (cod_produto, nome, valor) values (45, 'Gabinete Gamer Sharkoon VG7-W', 599.90);
insert into produto (cod_produto, nome, valor) values (46, 'Gabinete Gamer Husky Frost', 479.90);
insert into produto (cod_produto, nome, valor) values (47, 'Gabinete Gamer Husky Polar', 529.90);
insert into produto (cod_produto, nome, valor) values (48, 'Gabinete NOX COOLBAY MX2', 399.90);
insert into produto (cod_produto, nome, valor) values (49, 'Gabinete Gamer Corsair Carbide Series 175R', 629.90);
insert into produto (cod_produto, nome, valor) values (50, 'Gabinete ATX Sharkoon Som Virtual 7.1 Integrado', 299.90);
insert into produto (cod_produto, nome, valor) values (51, 'Gabinete Sharkoon TG5 Green Vidro', 999.90);
insert into produto (cod_produto, nome, valor) values (52, 'Processador AMD Ryzen 5 5600X', 1539.90);
insert into produto (cod_produto, nome, valor) values (53, 'Processador Intel Core i5-10400', 1079.90);
insert into produto (cod_produto, nome, valor) values (54, 'Processador Intel Core i3-10105', 779.90);
insert into produto (cod_produto, nome, valor) values (55, 'Processador AMD Ryzen 7 5700G', 1979.90);
insert into produto (cod_produto, nome, valor) values (56, 'Processador Intel Core i3-10100F', 569.90);
insert into produto (cod_produto, nome, valor) values (57, 'Processador AMD Ryzen 5 3600', 1339.90);
insert into produto (cod_produto, nome, valor) values (58, 'Processador AMD Ryzen 9 5900X', 3244.90);
insert into produto (cod_produto, nome, valor) values (59, 'Processador AMD Ryzen 7 5800X', 2184.90);
insert into produto (cod_produto, nome, valor) values (60, 'Processador Intel Core i7-10700F', 1899.90);
insert into produto (cod_produto, nome, valor) values (61, 'Processador Intel Core i5-10400F', 964.90);
insert into produto (cod_produto, nome, valor) values (62,'Memória Corsair Vengeance LPX', 219.90);
insert into produto (cod_produto, nome, valor) values (63,'Memória Crucial Ballistix 8GB DDR4 3000 Mhz', 229.90);
insert into produto (cod_produto, nome, valor) values (64,'Memória XPG Spectrix D45G, RGB, 8GB, 3600MHz', 299.90);
insert into produto (cod_produto, nome, valor) values (65,'Memória XPG Gammix D45, 8GB, 3200MHz, DDR4, CL16, Preta', 294.90);
insert into produto (cod_produto, nome, valor) values (66,'Memória Crucial Ballistix 8GB DDR4 3000 Mhz, CL15, Vermelho', 249.90);
insert into produto (cod_produto, nome, valor) values (67,'Memória XPG Spectrix D41 TUF, RGB, 8GB, 3200MHz, DDR4, CL16, Preta', 319.90);
insert into produto (cod_produto, nome, valor) values (68,'Memória Corsair Vengeance LPX, 8GB, 2400MHz, DDR4, CL16, Preto', 269.90);
insert into produto (cod_produto, nome, valor) values (69,'Memória XPG Hunter, 8GB, 3200MHz, DDR4, CL20, Para Notebook', 239.90);
insert into produto (cod_produto, nome, valor) values (70,'Memória Crucial Ballistix, 8GB, 2666MHz, DDR4, CL16, Vermelha', 259.90);
insert into produto (cod_produto, nome, valor) values (71,'Memória Corsair Vengeance RGB Pro, 8GB, 3200MHz, DDR4, CL16, Preta', 329.90);
insert into produto (cod_produto, nome, valor) values (72,'Monitor Gamer LG 25 IPS, Ultra Wide, 75 Hz', 1099.90);
insert into produto (cod_produto, nome, valor) values (73,'Monitor LG 21.5 LED, Full HD, HDMI/VGA', 899.90);
insert into produto (cod_produto, nome, valor) values (74,'Monitor LG 23.8 Full HD, IPS, HDMI, FreeSync', 999.90);
insert into produto (cod_produto, nome, valor) values (75,'Monitor Samsung 24 LED, Curvo, Wide, Full HD, HDMI/DisplayPort', 1099.90);
insert into produto (cod_produto, nome, valor) values (76,'Monitor Gamer LG 34 IPS, Curvo Ultra Wide, 144 Hz', 2899.90);
insert into produto (cod_produto, nome, valor) values (77,'Monitor Gamer Asus 23.8 IPS, Wide, 144 Hz', 1499.90);
insert into produto (cod_produto, nome, valor) values (78,'Monitor Gamer Ozone 24,5 LED, 144 Hz', 1299.90);
insert into produto (cod_produto, nome, valor) values (79, 'Monitor Philips 18.5 LED, HD, HDMI', 739.90);
insert into produto (cod_produto, nome, valor) values (80,'Monitor Gamer Asus 27 LED, Wide, 165 Hz', 1989.00);
insert into produto (cod_produto, nome, valor) values (81,'Monitor Gamer LG 29 IPS, Ultra Wide, 75 Hz', 1499.90);
insert into produto (cod_produto, nome, valor) values (82,'Placa-Mãe MSI B450M Pro-M2 Max p/ AMD AM4, m-ATX, DDR4', 389.90);
insert into produto (cod_produto, nome, valor) values (83,'Placa-mãe Gigabyte Aorus B450 Aorus M, AMD AM4, mATX, DDR4', 699.90);
insert into produto (cod_produto, nome, valor) values (84,'Placa Mãe Gigabyte H510M (rev.1.0), Intel LGA1200, ATX, DDR4', 649.90);
insert into produto (cod_produto, nome, valor) values (85,'Placa-Mãe MSI B360M Mortar, Intel LGA 1151, mATX, DDR4', 419.90);
insert into produto (cod_produto, nome, valor) values (86,'Placa Mãe Asus Prime H510M-E, Intel LGA 1200, microATX, DDR4', 699.90);
insert into produto (cod_produto, nome, valor) values (87,'Placa-Mãe Gigabyte Intel Ultra Durable (Rev. 1.0), Intel LGA1200, Micro ATX, DDR4', 629.90);
insert into produto (cod_produto, nome, valor) values (88,'Placa-Mãe ASRock B450M Steel Legend, AMD AM4, mATX, DDR4 - 90-MXB9Y0-A0BAYZ', 799.90);
insert into produto (cod_produto, nome, valor) values (89,'Placa Mãe Asus PRIME H510M-A, Intel Socket LGA1200, microATX, DDR4', 729.00);
insert into produto (cod_produto, nome, valor) values (90,'Placa-Mãe Asus TUF Gaming B550M-Plus, AMD B550, mATX, DDR4', 1189.90);
insert into produto (cod_produto, nome, valor) values (91,'Placa-Mãe Asus Prime B450M Gaming/BR, AMD AM4, mATX, DDR4', 629.90);
insert into produto (cod_produto, nome, valor) values (92,'Cadeira Gamer Husky Gaming Snow', 749.90);
insert into produto (cod_produto, nome, valor) values (93,'Cadeira Gamer ThunderX3 TGC12', 1499.90);
insert into produto (cod_produto, nome, valor) values (94,'Cadeira Gamer Alpha Gamer Vega', 1279.90);
insert into produto (cod_produto, nome, valor) values (95,'Cadeira ThunderX3 Ergonomic Yama1', 1649.90);
insert into produto (cod_produto, nome, valor) values (96,'Cadeira Gamer Husky Gaming Blizzard ', 1149.90);
insert into produto (cod_produto, nome, valor) values (97,'Cadeira Gamer DT3sports Elise', 1899.95);
insert into produto (cod_produto, nome, valor) values (98,'Cadeira Gamer Alpha Gamer Vega', 1279.90);
insert into produto (cod_produto, nome, valor) values (99,'Cadeira Gamer Fortrek Vickers', 979.90);
insert into produto (cod_produto, nome, valor) values (100,'Cadeira de Escritório Fratini Brooklyn', 999.90);
insert into produto (cod_produto, nome, valor) values (101,'Cadeira Gamer Corsair T2 Road Warrior', 2299.90);
insert into produto (cod_produto, nome, valor) values (102,'Headset Gamer HyperX Cloud Stinger Pink', 229.90);
insert into produto (cod_produto, nome, valor) values (103,'Headset Gamer HyperX Cloud Alpha S Azul', 649.90);
insert into produto (cod_produto, nome, valor) values (104,'Headset Gamer HyperX Cloud Stinger', 229.90);
insert into produto (cod_produto, nome, valor) values (105,'Headset Gamer Havit', 219.90);
insert into produto (cod_produto, nome, valor) values (106,'Headset Gamer Razer BlackShark V2 X', 299.90);
insert into produto (cod_produto, nome, valor) values (107,'Headset Gamer Sem Fio Logitech G533', 549.90);
insert into produto (cod_produto, nome, valor) values (108,'Headset Gamer Redragon Scylla', 129.90);
insert into produto (cod_produto, nome, valor) values (109,'Headset Gamer Redragon Ares',109.90);
insert into produto (cod_produto, nome, valor) values (110,'Headset Gamer Corsair Void Elite USB', 379.90);
insert into produto (cod_produto, nome, valor) values (111,'Headset Gamer Husky Tactical', 199.90);





